import fp from 'fastify-plugin'
import swagger, { SwaggerOptions } from 'fastify-swagger'

/**
 * Autogenerated Swagger-documentation
 * @see https://github.com/fastify/fastify-swagger
 */
export default fp<SwaggerOptions>(async (server, options) => {
  const routePrefix = '/swagger';

  server.register(swagger, {
    routePrefix,
    openapi: {
      info: {
        title: '',
        description: '',
        version: '0.1.0'
      }
    },
    exposeRoute: true,
  })

  server.get('/', async (request, reply) => {
    const { protocol, hostname } = request;
    reply.send({
      swaggerURL: `${protocol}://${hostname}${routePrefix}`
    })
  })
})
